### ISSUE TITLE
Refactor Security in order to manage metadata

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_back#27]
we were saving metadata on the security itself. instead lets make an asset record for asset data, and a metadata record for ipfs or other stuff. we'll make the metadata hierarchical because it is with a logo flag so that's easy to find.

**Comment by lastmeta** [comment]
in order to avoid duplication on pulling metadata for assets we should probably push the asset details into a stream where they are only delivered once (the stream wont broadcast the same asset details twice). then we can have a listener on that stream which not only saves the asset, but also pulls the metadatas (searching specifically for logo). I think this is preferable to saving the asset record when a transaction with that asset is discovered because saving it takes time and we may end up saving it a few times, and subsequently pulling data from ipfs a few times before it is actually saved to disk.

**Comment by Brock-Wood** [comment]
https://github.com/moontreeapp/raven_front/issues/8
